# Generated by Django 4.0.1 on 2022-02-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcalc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField(max_length=200, null=True)),
                ('num2', models.IntegerField(max_length=200, null=True)),
                ('num3', models.IntegerField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
